name: CI
on:
  pull_request:
    branches: ["master"]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          check-latest: true
          go-version: '1.20'
      - uses: actions/checkout@v2
      - run: go test ./...
      - run: go run ./test
